apiVersion: apps/v1
kind: Deployment
metadata:
 name: rockstar 
spec:
 replicas: 2
 selector:
  matchLabels:
   app: rockstar
 template:
  metadata:
   labels:
    app: rockstar
  spec:
   containers:
    - image: "saikiranreddykonda/rockiee"
      imagePullPolicy: Always 
      name: rockstar 
      ports:
       - containerPort: 80