apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend 
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 3 
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: sa-frontend 
    spec:
      containers:
      - image: saikiranreddykonda/sa-frontend-new
        imagePullPolicy: Always
        name: sa-frontend
        ports:
        - containerPort: 80